// PACKAGE_PATH
const POSTAGE = '/package-postage'
const ACTIVITY = '/package-activity'
const LEADER = '/package-leader'
const MAIN = '/pages'
/* eslint-disable */
export default {
  postage: {
    PACKAGE: POSTAGE,
    GOODS_DETAILS:`${POSTAGE}/goods-details`,
    ADDRESS_MANAGE:`${POSTAGE}/address-manage`,
    EDIT_ADDRESS:`${POSTAGE}/edit-address`,
    ORDER_LIST:`${POSTAGE}/order-list`,
    SUBMIT_ORDER:`${POSTAGE}/submit-order`,
    DISTRIBUTION_DETAIL:`${POSTAGE}/distribution-detail`,
    ORDER_DETAIL:`${POSTAGE}/order-detail`,
    GOODS_RECORD:`${POSTAGE}/goods-record`,
    // package-postage
  },
  activity: {
    PACKAGE: ACTIVITY,
    INVITEE:`${ACTIVITY}/invitee`,
    INVITATION_RULES:`${ACTIVITY}/invitation-rules`,
    INVITATION_INTRODUCTION:`${ACTIVITY}/invitation-introduction`,
    MY_RECORD:`${ACTIVITY}/my-record`,
    COMMODITY_CERTIFICATES:`${ACTIVITY}/commodity-certificates`,
    // package-activity
  },
  leader: {
    PACKAGE: LEADER,
    MINE_HOUSING: `${LEADER}/mine-housing`,
    REGIMENTAL_COMMANDER: `${LEADER}/regimental-commander`,
    REGIMENTAL_INFO: `${LEADER}/regimental-info`,
    RADAR: `${LEADER}/radar`,
    COUPON_SHARE: `${LEADER}/coupon-share`,
    YESTERDAY_SALE_MANAGER: `${LEADER}/yesterday-sale-manager`,
    GROUP_ORDER_DETAIL: `${LEADER}/group-order-detail`,
    AFTER_SALE_MANAGEMENT: `${LEADER}/after-sale-management`,
    DELIVERY_ORDER: `${LEADER}/delivery-order`,
    GROUP_WALLET: `${LEADER}/group-wallet`,
    INCOME_RECORD: `${LEADER}/income-record`,
    EXPEND_RECORD: `${LEADER}/expend-record`,
    WITHDRAW: `${LEADER}/withdraw`,
    BANK_CARD: `${LEADER}/bank-card`,
    SALE_SERVICE: `${LEADER}/sale-service`,
    FIND_PRODUCT: `${LEADER}/find-product`,
    DISTRIBUTION_COMMISSION: `${LEADER}/distribution-commission`,
    LEADER_INVITE: `${LEADER}/leader-invite`,
    LEADER_INVITE_SUCCESS: `${LEADER}/leader-invite-success`,
    APPLY_LEADER: `${LEADER}/apply-leader`,
    BIND_WX_WALLET:`${LEADER}/bind-wx-wallet`,
    // package-leader
  },
  main: {
    PACKAGE: MAIN,
    AFTER_ORDER: `${MAIN}/after-order`,
    AFTER_SERVICE: `${MAIN}/after-service`,
    APP_UPDATE: `${MAIN}/app-update`,
    CHOICENESS: `${MAIN}/choiceness`,
    CHOOSE_PICKUP: `${MAIN}/choose-pickup`,
    CLASSIFY: `${MAIN}/classify`,
    COLLAGE_DETAIL: `${MAIN}/collage-detail`,
    COUPON_CHOOSE: `${MAIN}/coupon-choose`,
    COUPON_CLASSIFY: `${MAIN}/coupon-classify`,
    COUPON_MINE: `${MAIN}/coupon-mine`,
    COUPON_TAKE: `${MAIN}/coupon-take`,
    ERROR: `${MAIN}/error`,
    FLASH_SALE_LIST: `${MAIN}/flash-sale-list`,
    GOODS_DETAIL: `${MAIN}/goods-detail`,
    GOODS_END: `${MAIN}/goods-end`,
    GOODS_RECORD: `${MAIN}/goods-record`,
    GOODS_SEARCH: `${MAIN}/goods-search`,
    LOGIN: `${MAIN}/login`,
    LOST: `${MAIN}/lost`,
    MINE: `${MAIN}/mine`,
    MY_GROUP_BUY: `${MAIN}/my-group-buy`,
    NOTICE: `${MAIN}/notice`,
    OPEN_LOCATION: `${MAIN}/open-location`,
    ORDER_DETAIL: `${MAIN}/order-detail`,
    ORDER_LIST: `${MAIN}/order-list`,
    OUT_HTML: `${MAIN}/out-html`,
    PAY_RESULT: `${MAIN}/pay-result`,
    RECOMMEND: `${MAIN}/recommend`,
    RECOMMEND_PAY: `${MAIN}/recommend-pay`,
    SHARE_ORDER: `${MAIN}/share-order`,
    SHOPPING_CART: `${MAIN}/shopping-cart`,
    SUBMIT_ORDER: `${MAIN}/submit-order`,
    INVITATION_CHOOSE:`${MAIN}/invitation-choose`,
    FREEZE_SHOP:`${MAIN}/freeze-shop`,
    // main
  }
}
